[2024-10-20T12:22:07.537+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T12:22:07.552+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia.download_pageview_zipfile manual__2024-10-20T11:21:21.376699+00:00 [queued]>
[2024-10-20T12:22:07.562+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia.download_pageview_zipfile manual__2024-10-20T11:21:21.376699+00:00 [queued]>
[2024-10-20T12:22:07.563+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-20T12:22:07.602+0100] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_pageview_zipfile> on 2024-10-20 11:21:21.376699+00:00
[2024-10-20T12:22:07.607+0100] {standard_task_runner.py:72} INFO - Started process 70007 to run task
[2024-10-20T12:22:07.611+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'wikipedia', 'download_pageview_zipfile', 'manual__2024-10-20T11:21:21.376699+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia/wikipedia.py', '--cfg-path', '/tmp/tmpstysuknk']
[2024-10-20T12:22:07.613+0100] {standard_task_runner.py:105} INFO - Job 2: Subtask download_pageview_zipfile
[2024-10-20T12:22:07.699+0100] {task_command.py:467} INFO - Running <TaskInstance: wikipedia.download_pageview_zipfile manual__2024-10-20T11:21:21.376699+00:00 [running]> on host zainab.
[2024-10-20T12:22:07.809+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='wikipedia' AIRFLOW_CTX_TASK_ID='download_pageview_zipfile' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T11:21:21.376699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T11:21:21.376699+00:00'
[2024-10-20T12:22:07.811+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-20T12:22:07.812+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-20T12:22:07.813+0100] {logging_mixin.py:190} INFO - Current task name:download_pageview_zipfile state:running start_date:2024-10-20 11:22:07.554779+00:00
[2024-10-20T12:22:07.815+0100] {logging_mixin.py:190} INFO - Dag name:wikipedia and current dag run status:running
[2024-10-20T12:22:07.816+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T12:22:09.246+0100] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/dags/wikipedia/wikipedia.py", line 34, in _download_pageview_zipfile
    request.urlretrieve(url,save_path)
  File "/usr/lib/python3.10/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/airflow/dags/wikipedia/pageview/pageview.gz'
[2024-10-20T12:22:09.385+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-20T12:22:09.387+0100] {logging_mixin.py:190} INFO - Task start:2024-10-20 11:22:07.554779+00:00 end:2024-10-20 11:22:09.385344+00:00 duration:1.830565
[2024-10-20T12:22:09.389+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_pageview_zipfile> dag:<DAG: wikipedia> dagrun:<DagRun wikipedia @ 2024-10-20 11:21:21.376699+00:00: manual__2024-10-20T11:21:21.376699+00:00, state:running, queued_at: 2024-10-20 11:21:21.527259+00:00. externally triggered: True>
[2024-10-20T12:22:09.391+0100] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/airflow/dags/wikipedia/pageview/pageview.gz'
[2024-10-20T12:22:09.392+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=wikipedia, task_id=download_pageview_zipfile, run_id=manual__2024-10-20T11:21:21.376699+00:00, execution_date=20241020T112121, start_date=20241020T112207, end_date=20241020T112209
[2024-10-20T12:22:09.488+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T12:22:09.490+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task download_pageview_zipfile ([Errno 2] No such file or directory: '/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/airflow/dags/wikipedia/pageview/pageview.gz'; 70007)
Traceback (most recent call last):
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/dags/wikipedia/wikipedia.py", line 34, in _download_pageview_zipfile
    request.urlretrieve(url,save_path)
  File "/usr/lib/python3.10/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/zaina/Documents/Core_Data_Engineering/airflow/airflow_coresentiment_Data_pipeline/airflow/airflow/dags/wikipedia/pageview/pageview.gz'
[2024-10-20T12:22:09.561+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-20T12:22:09.597+0100] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-20T12:22:09.613+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
